image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: open-preview

tasks:
  - name: Dependencies and credentials
    init: make bootstrap
    command: make server
  - name: Install twilio-cli + serverless-toolkit plugin
    init: make cli
