image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: open-preview

tasks:
  - name: Dependencies and credentials
    init: make bootstrap
    command: >
      npm run start
      ./get-creds.mjs
  - name: Install twilio-cli + serverless-toolkit plugin
    init: >
      npm i -g twilio-cli
		  twilio plugins:install @twilio-labs/plugin-serverless
